### ISSUE TITLE
Can't extract archives

### ISSUE THREAD

**Issue by JimLGray** [andrebroekman/PASMVS#1]
Hi,

When I try to open PASMVS_576p.tar.xz I get the error message shown below. I get the same issue with the high resolution data. I have also tried to download and extract the data on a Mac to see if it was a linux only problem. I wonder if the archives are corrupted somehow. It looks like a very promising dataset for the problems I'm trying to look at.

![image](https://github.com/user-attachments/assets/dd51af5b-fe84-411f-adff-57a7e77ed225)

Thank you,

Jim

**Comment by andrebroekman** [comment]
Hi @JimLGray; as we communicated via email, 7Zip appears to be working to extract the archives. Leaving this comment here for any future inquiries or others using the dataset.
